name: twod-analysis-kit-docs
channels:

  - conda-forge

dependencies:
    # Base depends
  - python
  - pip

  - mdanalysis-sphinx-theme >=1.0.1
  - imageio>=2.36.0
  - pandas
  - seaborn
  - nglview
  - networkx
    # Pip-only installs
  - pip:
    - imageio>=2.36.0

